// Generates Supabase seed migrations from the prototype's JSON data:
//   site/data/curriculum/*.json  -> 20260609000002_catalog_seed.sql
//   site/data/questions-*.json   -> 20260609000003_questions_seed.sql
// Rows are embedded as one dollar-quoted jsonb literal per table and inserted
// via jsonb_to_recordset, so no per-value SQL escaping is needed.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const curriculumDir = join(here, "..", "src", "data", "curriculum");
const questionsDir = join(root, "site", "data");
const migrationsDir = join(root, "supabase", "migrations");

const TAG = "$NDTA_SEED$";
const quote = (rows) => {
  const json = JSON.stringify(rows);
  if (json.includes("$NDTA_SEED$")) throw new Error("dollar-quote tag collision in data");
  return TAG + json + TAG;
};

// Course-level metadata not stored in the curriculum JSON
const COURSE_META = {
  ut:    { sort: 1, examMethod: "UT",  summary: "Sound wave physics, transducers, calibration, straight beam and angle beam techniques, thickness measurement, weld inspection, and evaluation to code." },
  rt:    { sort: 2, examMethod: "RT",  summary: "Radiation sources, exposure technique, film and digital systems, image quality indicators, and interpretation of weldments and castings." },
  mt:    { sort: 3, examMethod: "MPI", summary: "Magnetization theory, yokes and wet horizontal benches, continuous and residual methods, field indicators, and evaluation per industry specifications." },
  pt:    { sort: 4, examMethod: "LPI", summary: "Type I fluorescent and Type II visible penetrant systems, dwell and processing controls, developers, and evaluation of indications." },
  et:    { sort: 5, examMethod: "ECT", summary: "Electromagnetic induction, impedance plane analysis, probe selection, surface and bolt-hole inspection, conductivity testing, and eddy current array techniques." },
  vt:    { sort: 6, examMethod: null,  summary: "Direct and remote visual inspection, lighting and measurement requirements, borescope operation and technique, and acceptance criteria." },
  basic: { sort: 7, examMethod: null,  summary: "Materials and processes, discontinuity origins, and a survey of all major NDT methods — the starting point for new technicians and the Level III Basic exam." },
  rad:   { sort: 8, examMethod: null,  summary: "Radiation fundamentals, dose limits, survey instruments, regulations, and emergency procedures for industrial radiographers and card holders." },
};

const courses = [], levels = [], modules = [], lessons = [];
for (const id of Object.keys(COURSE_META)) {
  const c = JSON.parse(readFileSync(join(curriculumDir, `${id}.json`), "utf8"));
  const meta = COURSE_META[id];
  courses.push({
    id: c.id, code: c.code, name: c.name, cp105: c.cp105 ?? null,
    hours: c.hours ?? {}, exam_method: meta.examMethod, summary: meta.summary,
    jurisdiction_note: c.jurisdictionNote ?? null, sort: meta.sort,
  });
  c.levels.forEach((L, li) => {
    const levelId = `${c.id}-${L.level}`;
    levels.push({
      id: levelId, course_id: c.id, level: String(L.level),
      target_hours: L.targetHours ?? 0, description: L.description ?? null,
      final_exam: L.finalExam ?? null, sort: li,
    });
    L.modules.forEach((m, mi) => {
      modules.push({
        id: m.id, level_id: levelId, title: m.title, cp_section: m.cpSection ?? null,
        hours: m.hours ?? 0, module_quiz: m.moduleQuiz ?? null, sort: mi,
      });
      m.lessons.forEach((l, lsi) => {
        lessons.push({
          id: l.id, module_id: m.id, title: l.title, minutes: l.minutes ?? 0,
          objectives: l.objectives ?? [], topics: l.topics ?? [],
          media: l.media ?? [], knowledge_check: l.check ?? null, sort: lsi,
        });
      });
    });
  });
}

const catalogSql = `-- NDT Academy — catalog seed (generated by web/scripts/generate-seed.mjs; do not hand-edit)
insert into public.courses (id, code, name, cp105, hours, exam_method, summary, jurisdiction_note, sort)
select id, code, name, cp105, hours, exam_method, summary, jurisdiction_note, sort
from jsonb_to_recordset(${quote(courses)}::jsonb)
  as t(id text, code text, name text, cp105 text, hours jsonb, exam_method text, summary text, jurisdiction_note text, sort int)
on conflict (id) do nothing;

insert into public.course_levels (id, course_id, level, target_hours, description, final_exam, sort)
select id, course_id, level, target_hours, description, final_exam, sort
from jsonb_to_recordset(${quote(levels)}::jsonb)
  as t(id text, course_id text, level text, target_hours numeric, description text, final_exam jsonb, sort int)
on conflict (id) do nothing;

insert into public.modules (id, level_id, title, cp_section, hours, module_quiz, sort)
select id, level_id, title, cp_section, hours, module_quiz, sort
from jsonb_to_recordset(${quote(modules)}::jsonb)
  as t(id text, level_id text, title text, cp_section text, hours numeric, module_quiz jsonb, sort int)
on conflict (id) do nothing;

insert into public.lessons (id, module_id, title, minutes, objectives, topics, media, knowledge_check, sort)
select id, module_id, title, minutes, objectives, topics, media, knowledge_check, sort
from jsonb_to_recordset(${quote(lessons)}::jsonb)
  as t(id text, module_id text, title text, minutes int, objectives jsonb, topics jsonb, media jsonb, knowledge_check jsonb, sort int)
on conflict (id) do nothing;
`;
writeFileSync(join(migrationsDir, "20260609000002_catalog_seed.sql"), catalogSql);

const qRows = [];
for (const m of ["UT", "RT", "MPI", "LPI", "ECT"]) {
  const bank = JSON.parse(readFileSync(join(questionsDir, `questions-${m}.json`), "utf8"));
  for (const q of bank) {
    if (!q.q || !Array.isArray(q.o) || q.o.length !== 4 || q.o.some(o => !o)) continue;
    if (typeof q.c !== "number" || q.c < 0 || q.c > 3) continue;
    qRows.push({ method: m, level: q.l, question: q.q, options: q.o, correct: q.c });
  }
}
// One INSERT per 500-question chunk; "-- CHUNK --" markers let the HTTPS
// apply script post pieces separately (network here blocks raw Postgres ports).
const CHUNK = 500;
const inserts = [];
for (let i = 0; i < qRows.length; i += CHUNK) {
  inserts.push(`insert into public.questions (method, level, question, options, correct)
select method, level, question, options, correct
from jsonb_to_recordset(${quote(qRows.slice(i, i + CHUNK))}::jsonb)
  as t(method text, level int, question text, options jsonb, correct int);`);
}
const questionsSql = `-- NDT Academy — question bank seed (generated; content flagged generic_rewrite_pending by default)
${inserts.join("\n-- CHUNK --\n")}
`;
writeFileSync(join(migrationsDir, "20260609000003_questions_seed.sql"), questionsSql);

console.log(`courses=${courses.length} levels=${levels.length} modules=${modules.length} lessons=${lessons.length} questions=${qRows.length}`);
